# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nihilist Movie Club
email: nihilistMovieClub@gmail.com
tagline: "a pointless record of our madness"
description: > # this means to ignore newlines until "baseurl:"
  A movie club where we fervently believe no movie can make a definitive
  claim to be better than any other. Thus, while we sometimes choose movies
  that have a particular significance to one or more of the members, we
  ultimately expect it to be no better than using a random generator.
baseurl: "" # the subpath of your site, e.g. /blog
url: "nihilistmovie.club" # the base hostname & protocol for your site
twitter_username: "@nihilistMovies"
github_username:

# Build settings
markdown: kramdown
